#tipos simulaciones
STATIC_SIM_SELECTED     = "-STATIC_SIM_SELECTED-"
DINAMIC_SIM_SELECTED    = "-DINAMIC_SIM_SELECTED-"

#datos sesión
NOMBRE_INPUT            = "-NOMBRE_INPUT-"
DESCRIPCION_INPUT       = "-DESCRIPCION_INPUT-"
CONFIG_INPUT            = "-CONFIG_INPUT-"
CONFIG_FILE_TEXT        = "-CONFIG_FILE_TEXT-"
CONFIG_FILE_BROWSER     = "-CONFIG_FILE_BROWSER-"
CARGAR_SESION_INPUT     = "-CARGAR_SESION_INPUT-"
CARGAR_CONFIG_INPUT     = "-CARGAR_CONFIG_INPUT-"

#fecha y lugar
RESOLUCION_INPUT        = "-RESOLUCION_INPUT-"
FECHA_INICIO            = "-FECHA_INICIO-"
FECHA_INICIO_INPUT      = "-FECHA_INICIO_INPUT-"
FECHA_FIN               = "-FECHA_FIN-"
FECHA_FIN_INPUT         = "-FECHA_FIN_INPUT-"
HORA_INICIO_INPUT       = "-HORA_INICIO_INPUT-"
MINUTO_INICIO_INPUT     = "-MINUTO_INICIO_INPUT-"
HORA_FINAL_INPUT        = "-HORA_FINAL_INPUT-"
MINUTO_FINAL_INPUT      = "-MINUTO_FINAL_INPUT-"
LUGAR_INPUT             = "-LUGAR_INPUT-"
LATITUD_INPUT           = "-LATITUD_INPUT-"
LONGITUD_INPUT          = "-LONGITUD_INPUT-"

#geometría
DIM_X_INPUT             = "-DIM_X_INPUT-"
DIM_Y_INPUT             = "-DIM_Y_INPUT-"
CURVATURA_INPUT         = "-CURVATURA_INPUT-"
ORIENTACION_INPUT       = "-ORIENTACION_INPUT-"

#configuración célula
TECNOLOGIA_INPUT        = "-TECNOLOGIA_INPUT-"
NUM_CEL_X_INPUT         = "-NUM_CEL_X_INPUT-"
NUM_CEL_Y_INPUT         = "-NUM_CEL_Y_INPUT-"
CONEXION_INPUT          = "-CONEXION_INPUT-"

#datos radiación
CLEAR_SKY               = "-CLEAR_SKY-"
TMY                     = "-TMY-"
DATA_METEO              = "-DATA_METEO-"
TMY_INPUT               = "-TMY_INPUT-"
DATA_METEO_INPUT        = "-DATA_METEO_INPUT-"
DATA_METEO_BROWSER      = "-DATA_METEO_BROWSER-"

#datos parametrización
PARAMETRIC_VAR_INPUT    = "-PARAMETRIC_VAR_INPUT-"
LIM_SUP_INPUT           = "-LIM_SUP_INPUT-"
LIM_INF_INPUT           = "-LIM_INF_INPUT-"
RANGO_INPUT             = "-RANGO_INPUT-"
VALUES_PARAMETRIC_INPUT = "-VALUES_PARAMETRIC_INPUT-"

#tipos resultados
RECURSO_SOLAR_INPUT     = "-RECURSO_SOLAR_INPUT-"
CURVAS_IV_INPUT         = "-CURVAS_IV_INPUT-"
GEN_ELECTRICA_INPUT     = "-GEN_ELECTRICA_INPUT-"

#vista resultados
TAB_SESION              = "-TAB_SESION-"
TAB_CONFIG              = "-TAB_CONFIG-"
TAB_RESULTADOS          = "-TAB_RESULTADOS-"
TAB_GRUPO               = "-TAB_GRUPO-"
FRAME_RESULTADOS        = "-FRAME_RESULTADOS-"
VALOR_PARAMETRICA       = "-VALOR_PARAMETRICA-"
RESULTADO_INPUT         = "-RESULTADO-INPUT-"
RECURSO_SOLAR_IMAGE     = "-RECURSO_SOLAR_IMAGE-"
CURVAS_IV_IMAGE         = "-CURVAS_IV_IMAGE-"
GEN_ELECTRICA_IMAGE     = "-GEN_ELECTRICA_IMAGE-"
PARAM_VAR_TEXT          = "-PARAM_VAR_TEXT-"
RECURSO_SOLAR_TEXT      = "Recurso solar"
CURVAS_IV_TEXT          = "Curva I-V"
GEN_ELECTRICA_TEXT      = "Generacion electrica"
RESULT_IMAGE            = "-RESULT_IMAGE-"

#elementos auxiliares
GUARDAR_INPUT           = "-GUARDAR_INPUT-"
CARGAR_DATOS_INPUT      = "-CARGAR_DATOS_INPUT-"
SIMULAR_INPUT           = "-SIMULAR_INPUT-"
RIGHT_CLICK             = "+RIGHT_CLICK+"
BACK                    = "-BACK-"
POPUP_INPUT             = "-POPUP_INPUT-"
RADIATION_TYPE_GROUP    = "-RADIATION_TYPE_GROUP"
INIT_SIMULATION         = "-INIT_SIMULATION-"
GENERAR_CONFIG          = "-GENERAR_CONFIG-"

ANACONDA_EXECUTE        = "python"
MODEL_SCRIPT            = "src/ficheros_datos_accede.py"
IMAGES_PATH             = "data/images/"
SESSIONS_PATH           = "sessions/"
CONNECTIONS_DEFAULT_PATH= "data/connections/"
RESULT_FILE             = "result_file.yaml"
CONFIG_FILE_NAME        = "config_static_sim_data.yaml"