#tipos simulaciones
STATIC_SIM_SELECTED     = "-STATIC_SIM_SELECTED-"
DINAMIC_SIM_SELECTED    = "-DINAMIC_SIM_SELECTED-"

#fecha y lugar
RESOLUCION_INPUT        = "-RESOLUCION_INPUT-"
FECHA_INICIO            = "-FECHA_INICIO-"
FECHA_INICIO_INPUT      = "-FECHA_INICIO_INPUT-"
FECHA_FIN               = "-FECHA_FIN-"
FECHA_FIN_INPUT         = "-FECHA_FIN_INPUT-"
HORA_INICIO_INPUT       = "-HORA_INICIO_INPUT-"
MINUTO_INICIO_INPUT     = "-MINUTO_INICIO_INPUT-"
HORA_FINAL_INPUT        = "-HORA_FINAL_INPUT-"
MINUTO_FINAL_INPUT      = "-MINUTO_FINAL_INPUT-"
LUGAR_INPUT             = "-LUGAR_INPUT-"
LATITUD_INPUT           = "-LATITUD_INPUT-"
LONGITUD_INPUT          = "-LONGITUD_INPUT-"

#geometría
DIM_X_INPUT                 = "-DIM_X_INPUT-"
DIM_Y_INPUT                 = "-DIM_Y_INPUT-"
CURVATURA_INPUT         = "-CURVATURA_INPUT-"
ORIENTACION_INPUT       = "-ORIENTACION_INPUT-"

#configuración célula
TECNOLOGIA_INPUT        = "-TECNOLOGIA_INPUT-"
NUM_CEL_X_INPUT         = "-NUM_CEL_X_INPUT-"
NUM_CEL_Y_INPUT         = "-NUM_CEL_Y_INPUT-"
CONEXION_INPUT          = "-CONEXION_INPUT-"

#datos radiación
CLEAR_SKY               = "-CLEAR_SKY-"
TMY                     = "-TMY-"
DATA_METEO              = "-DATA_METEO-"
TMY_INPUT               = "-TMY_INPUT-"
DATA_METEO_INPUT        = "-DATA_METEO_INPUT-"
DATA_METEO_BROWSER      = "-DATA_METEO_BROWSER-"

#tipos resultados
RECURSO_SOLAR_INPUT     = "-RECURSO_SOLAR_INPUT-"
CURVAS_IV_INPUT         = "-CURVAS_IV_INPUT-"
GEN_ELECTRICA_INPUT     = "-GEN_ELECTRICA_INPUT-"

#elementos auxiliares
GUARDAR_INPUT           = "-GUARDAR_INPUT-"
CARGAR_DATOS_INPUT      = "-CARGAR_DATOS_INPUT-"
SIMULAR_INPUT           = "-SIMULAR_INPUT-"
RIGHT_CLICK             = "+RIGHT_CLICK+"
BACK                    = "-BACK-"
POPUP_INPUT             = "-POPUP_INPUT-"
RADIATION_TYPE_GROUP    = "-RADIATION_TYPE_GROUP"
INIT_SIMULATION         = "-INIT_SIMULATION-"